services:
  spark:
    build: 
      context: spark-master
      dockerfile: Dockerfile
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7077:7077'
      - '4040:4040'
    extra_hosts:
      - "host.docker.internal:${HOST_IP}"
    volumes:
      - 'E:\projects\spark_cluster\tmp:/tmp'
      - 'E:\projects\spark_cluster\data-bucket:/data:rw'
      - 'E:\projects\spark_cluster\scripts:/scripts:rw'
      - 'E:\projects\spark_cluster\jar_files:/extra_jars'
  spark-worker:
    image: docker.io/bitnami/spark:3.5.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    depends_on:
      - spark
    extra_hosts:
      - "host.docker.internal:${HOST_IP}"
    volumes:
        - 'E:\projects\spark_cluster\tmp:/tmp'
        - 'E:\projects\spark_cluster\data-bucket:/data:rw'
        - 'E:\projects\spark_cluster\jar_files:/extra_jars'
  db-warehouse:
    image: postgres:12.21
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - 'E:\projects\spark_cluster\dbdata:/var/lib/postgresql/data:rw'

  db-pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
    depends_on:
      - db-warehouse